### ISSUE TITLE
[Forge 1.20.1] Enabling the "required tool only" option in the config is making fist mining really slow.

### ISSUE THREAD

**Issue by vizthex123** [PandaMods-Dev/Pandas-Falling-Trees#66]
Only had this issue in the newest version of the mod (0.12), as it worked fine in  0.11 (didn't affect fist speed while affecting axe speed).

Edit: It was a Fir tree, and it seems like this bug only applies to Biomes o' Plenties trees.

**Comment by PandaDap2006** [comment]
I check it out.

**Comment by ThePandaOliver** [comment]
It should have been fixed in the latest update.

**Comment by vizthex123** [comment]
awesome, thanks.
