### ISSUE TITLE
[Fabric 1.19.2] Latest mod version (0.12) crashes the game

### ISSUE THREAD

**Issue by vizthex123** [PandaMods-Dev/Pandas-Falling-Trees#67]
Seems like the version only supports 1.20.

Log:
[latest.log](https://github.com/PandaDap2006/Pandas-Falling-Trees/files/15055323/latest.log)

**Comment by PandaDap2006** [comment]
Thanks for telling me. Seems I forgot to set the required version to 1.19.2 for the fabric version.

**Comment by ThePandaOliver** [comment]
Is fixed
