### ISSUE TITLE
[BUG] Connected Leaves from other trees fall when I chop a single tree

### ISSUE THREAD

**Issue by Camawama** [PandaMods-Dev/Pandas-Falling-Trees#72]
Forge 47.2.32
Falling Trees: 0.12.1
Panda Lib: 0.2.1

The issue only recently started becoming more prevalent, possibly from recent mod updates. If too many leaves fall at once, I get kicked from my world for an overflow error.

![2024-06-01_11 22 38](https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/43620900/7c2a79d0-00c9-4b9d-9d21-1b8fc6cb6f3c)
![2024-06-01_11 22 40](https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/43620900/19977398-6acb-45f9-9067-1f4d8b5b1b14)

Log with the world crash
[latest.log](https://github.com/user-attachments/files/15522557/latest.log)

**Comment by Camawama** [comment]
It's still happening but this time I got some crash reports.

[crash-2024-06-08_10.25.08-server.txt](https://github.com/user-attachments/files/15750241/crash-2024-06-08_10.25.08-server.txt)

**Comment by Camawama** [comment]
![image](https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/43620900/316448a9-e4ee-41e3-ab01-11cac2861c0d)

**Comment by PandaDap2006** [comment]
Check the common config, the mushroom tree type might have the tags for leaves and logs int its filters.

**Comment by Camawama** [comment]
that's the thing. I wasn't chopping a mushroom. It was just a normal tree.

**Comment by Camawama** [comment]
https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/43620900/abb67583-648c-42da-ba89-532860f103e9

**Comment by Camawama** [comment]
Update: Disabling mushroom in the config fixed the crash for trees.

**Comment by ThePandaOliver** [comment]
For anyone in the future having this problem, try and delete your `fallingtrees_common.json` file to regenerate the config.
