### ISSUE TITLE
Mixed log/leaf custom trees not compatible with the mod

### ISSUE THREAD

**Issue by TheDarkPanther** [PandaMods-Dev/Pandas-Falling-Trees#86]
I tried punching a custom tree down with the mod on the logs are mangrove logs with jungle leaves, could this be fixed please? 
![2024-07-19_10 14 11](https://github.com/user-attachments/assets/c15ec5df-8c87-4ff2-97b4-5c4957eb1313)
![2024-07-19_10 14 06](https://github.com/user-attachments/assets/db7289d7-5ab7-4e64-a587-f7f400e20afc)

I use a lot of custom tree schematics in my maps and it's hard to find a good tree chopping mod that look and feels right/good. 

This is the only one that feels okay..

**Comment by ThePandaOliver** [comment]
Add the logs and leaves to the standard tree filter in the common config.
Sorry about the long wait.
