### ISSUE TITLE
How do I extend the config's tree capacity.

### ISSUE THREAD

**Issue by makumaku1974** [PandaMods-Dev/Pandas-Falling-Trees#88]
Basically, what I meant was how do i edit the axes range to cut the tree. For example a long redwood tree from biomes o plenty... It is seemingly hard to cut it by default and with the mod installed. Still can't find the exact range or exact limit, needed to cut through the tree so the animation falling tree would start.

Ps. This is only a config help and not the mod itself.

**Comment by ThePandaOliver** [comment]
Go into the `fallingtrees_common.json` file and find the option `maxLogAmount` change the value to something higher and try again.

Sorry for the wait.

**Comment by makumaku1974** [comment]
It's all great, ill be installing it again.
