### ISSUE TITLE
Need to add bark

### ISSUE THREAD

**Issue by Vitokhv** [PandaMods-Dev/Pandas-Falling-Trees#90]
Need to add bark,
so that the axe strikes reach the middle of the tree, as in HT's TreeChop mod

![chopping-birch](https://github.com/user-attachments/assets/947b894f-5947-49b2-b644-19de007b4879)

![screenshot_15973](https://github.com/user-attachments/assets/14665952-e0fa-4603-9f66-2fc9c30906e8)

or mods can work together?
although on version 1.20.4 and 1.21 the second mod has no updates

need for version Fabric 0.16.0+ (Minecraft 1.20.1)
need for version Fabric 0.16.0+ (Minecraft 1.20.4)
need for version Fabric 0.16.0+ (Minecraft 1.21)

**Comment by PandaDap2006** [comment]
Sorry, but this feature will not be added, this will be exclusive for HT's TreeChop.
If you want to use this with Falling Trees, then you can install them together if you want it for a version that HT's TreeChop is not supporting, then you will have to ask Hammertater.
